//! User-facing display preferences.
//!
//! Everything in this module is plain data that the user can toggle in the
//! Settings window. It derives `serde`'s traits, but nothing persists it yet:
//! preferences are reset each launch. Adding load/save only needs to call
//! `serde_json` on a `DisplayConfig` here; the derives are already in place.
//!
//! Keeping it separate from [`crate::app`] means the app state struct stays
//! small and readable: it holds one `DisplayConfig` instead of ~140 columns.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DisplayConfig {
    pub show_iso_chart: bool,
    pub show_aperture_chart: bool,
    pub show_focal_chart: bool,
    pub show_camera_table: bool,
    pub show_lens_table: bool,
    pub show_photo_table: bool,
    pub chart_type: ChartType,
    pub aperture_scale: ApertureScale,
    pub max_table_rows: usize,
    pub photo_table_columns: PhotoTableColumns,
}

impl Default for DisplayConfig {
    fn default() -> Self {
        Self {
            show_iso_chart: true,
            show_aperture_chart: true,
            show_focal_chart: true,
            show_camera_table: true,
            show_lens_table: true,
            show_photo_table: true,
            chart_type: ChartType::Bars,
            aperture_scale: ApertureScale::Linear,
            max_table_rows: 10,
            photo_table_columns: PhotoTableColumns::default(),
        }
    }
}

/// Which set of EXIF tags is available depends on the container: JPEG writes a
/// rich EXIF block, RAW files vary by camera maker, and some tags (GPS,
/// environmental data) only exist on some bodies.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PhotoTableColumns {
    // Always shown (defaults)
    pub show_file: bool,
    pub show_date: bool,
    pub show_aperture: bool,
    pub show_focal_length: bool,
    pub show_camera: bool,
    pub show_lens: bool,
    pub show_type: bool,

    // JPEG only
    pub show_make: bool,
    pub show_software: bool,
    pub show_artist: bool,
    pub show_copyright: bool,
    pub show_lens_make: bool,
    pub show_lens_specification: bool,
    pub show_exposure_time: bool,
    pub show_shutter_speed_value: bool,
    pub show_exposure_program: bool,
    pub show_exposure_mode: bool,
    pub show_exposure_bias_value: bool,
    pub show_metering_mode: bool,
    pub show_flash: bool,
    pub show_white_balance: bool,
    pub show_color_space: bool,
    pub show_scene_capture_type: bool,
    pub show_gain_control: bool,
    pub show_contrast: bool,
    pub show_saturation: bool,
    pub show_sharpness: bool,
    pub show_body_serial_number: bool,
    pub show_camera_owner_name: bool,
    pub show_gps_latitude: bool,
    pub show_gps_longitude: bool,
    pub show_gps_altitude: bool,
    pub show_orientation: bool,
    pub show_x_resolution: bool,
    pub show_y_resolution: bool,
    pub show_temperature: bool,
    pub show_humidity: bool,
    pub show_pressure: bool,
    pub show_exif_version: bool,
    pub show_flashpix_version: bool,
    pub show_sensing_method: bool,

    // RAW only
    pub show_raw_width: bool,
    pub show_raw_height: bool,
    pub show_raw_cpp: bool,
    pub show_raw_bps: bool,
    pub show_black_level: bool,
    pub show_white_level: bool,
    pub show_active_area: bool,
    pub show_crop_area: bool,
    pub show_raw_cfa_pattern: bool,
    pub show_color_matrix_1: bool,
    pub show_color_matrix_2: bool,
    pub show_wb_coeffs: bool,
    pub show_xyz_to_cam: bool,
    pub show_clean_make: bool,
    pub show_clean_model: bool,
    pub show_default_scale: bool,
    pub show_best_quality_scale: bool,

    // Both (available in both but not defaults)
    pub show_photographic_sensitivity: bool,
    pub show_iso_speed: bool,
    pub show_recommended_exposure_index: bool,
    pub show_standard_output_sensitivity: bool,
    pub show_sensitivity_type: bool,
    pub show_aperture_value: bool,
    pub show_max_aperture_value: bool,
    pub show_focal_length_in_35mm_film: bool,
    pub show_focal_plane_x_resolution: bool,
    pub show_focal_plane_y_resolution: bool,
    pub show_focal_plane_resolution_unit: bool,
    pub show_flash_energy: bool,
    pub show_subject_distance: bool,
    pub show_subject_distance_range: bool,
    pub show_custom_rendered: bool,
    pub show_gamma: bool,
    pub show_image_description: bool,
    pub show_user_comment: bool,
    pub show_maker_note: bool,
    pub show_image_unique_id: bool,
    pub show_lens_serial_number: bool,
    pub show_date_time_original: bool,
    pub show_date_time_digitized: bool,
    pub show_sub_sec_time: bool,
    pub show_sub_sec_time_original: bool,
    pub show_sub_sec_time_digitized: bool,
    pub show_offset_time: bool,
    pub show_offset_time_original: bool,
    pub show_offset_time_digitized: bool,
    pub show_gps_latitude_ref: bool,
    pub show_gps_longitude_ref: bool,
    pub show_gps_altitude_ref: bool,
    pub show_gps_timestamp: bool,
    pub show_gps_satellites: bool,
    pub show_gps_status: bool,
    pub show_gps_measure_mode: bool,
    pub show_gps_dop: bool,
    pub show_gps_speed: bool,
    pub show_gps_speed_ref: bool,
    pub show_gps_track: bool,
    pub show_gps_track_ref: bool,
    pub show_gps_img_direction: bool,
    pub show_gps_img_direction_ref: bool,
    pub show_gps_map_datum: bool,
    pub show_gps_date_stamp: bool,
    pub show_gps_processing_method: bool,
    pub show_gps_area_information: bool,
    pub show_gps_differential: bool,
    pub show_gps_h_positioning_error: bool,
    pub show_resolution_unit: bool,
    pub show_photometric_interpretation: bool,
    pub show_compression: bool,
    pub show_bits_per_sample: bool,
    pub show_samples_per_pixel: bool,
    pub show_planar_configuration: bool,
    pub show_ycbcr_sub_sampling: bool,
    pub show_ycbcr_positioning: bool,
    pub show_reference_black_white: bool,
    pub show_white_point: bool,
    pub show_primary_chromaticities: bool,
    pub show_ycbcr_coefficients: bool,
    pub show_water_depth: bool,
    pub show_acceleration: bool,
    pub show_camera_elevation_angle: bool,
    pub show_components_configuration: bool,
    pub show_compressed_bits_per_pixel: bool,
    pub show_file_source: bool,
    pub show_scene_type: bool,
    pub show_cfa_pattern: bool,
    pub show_device_setting_description: bool,
    pub show_subject_area: bool,
    pub show_related_sound_file: bool,
    pub show_spatial_frequency_response: bool,
    pub show_spectral_sensitivity: bool,
    pub show_oecf: bool,
    pub show_width: bool,
    pub show_height: bool,
    pub show_raw_orientation: bool,
    pub show_fuji_rotation_width: bool,
    pub show_camera_mode: bool,
    pub show_remark: bool,
}

impl Default for PhotoTableColumns {
    fn default() -> Self {
        Self {
            // Defaults - always shown
            show_file: true,
            show_date: true,
            show_aperture: true,
            show_focal_length: true,
            show_camera: true,
            show_lens: true,
            show_type: true,

            // JPEG only - hidden by default
            show_make: false,
            show_software: false,
            show_artist: false,
            show_copyright: false,
            show_lens_make: false,
            show_lens_specification: false,
            show_exposure_time: false,
            show_shutter_speed_value: false,
            show_exposure_program: false,
            show_exposure_mode: false,
            show_exposure_bias_value: false,
            show_metering_mode: false,
            show_flash: false,
            show_white_balance: false,
            show_color_space: false,
            show_scene_capture_type: false,
            show_gain_control: false,
            show_contrast: false,
            show_saturation: false,
            show_sharpness: false,
            show_body_serial_number: false,
            show_camera_owner_name: false,
            show_gps_latitude: false,
            show_gps_longitude: false,
            show_gps_altitude: false,
            show_orientation: false,
            show_x_resolution: false,
            show_y_resolution: false,
            show_temperature: false,
            show_humidity: false,
            show_pressure: false,
            show_exif_version: false,
            show_flashpix_version: false,
            show_sensing_method: false,

            // RAW only - hidden by default
            show_raw_width: false,
            show_raw_height: false,
            show_raw_cpp: false,
            show_raw_bps: false,
            show_black_level: false,
            show_white_level: false,
            show_active_area: false,
            show_crop_area: false,
            show_raw_cfa_pattern: false,
            show_color_matrix_1: false,
            show_color_matrix_2: false,
            show_wb_coeffs: false,
            show_xyz_to_cam: false,
            show_clean_make: false,
            show_clean_model: false,
            show_default_scale: false,
            show_best_quality_scale: false,

            // Both - hidden by default
            show_photographic_sensitivity: false,
            show_iso_speed: false,
            show_recommended_exposure_index: false,
            show_standard_output_sensitivity: false,
            show_sensitivity_type: false,
            show_aperture_value: false,
            show_max_aperture_value: false,
            show_focal_length_in_35mm_film: false,
            show_focal_plane_x_resolution: false,
            show_focal_plane_y_resolution: false,
            show_focal_plane_resolution_unit: false,
            show_flash_energy: false,
            show_subject_distance: false,
            show_subject_distance_range: false,
            show_custom_rendered: false,
            show_gamma: false,
            show_image_description: false,
            show_user_comment: false,
            show_maker_note: false,
            show_image_unique_id: false,
            show_lens_serial_number: false,
            show_date_time_original: false,
            show_date_time_digitized: false,
            show_sub_sec_time: false,
            show_sub_sec_time_original: false,
            show_sub_sec_time_digitized: false,
            show_offset_time: false,
            show_offset_time_original: false,
            show_offset_time_digitized: false,
            show_gps_latitude_ref: false,
            show_gps_longitude_ref: false,
            show_gps_altitude_ref: false,
            show_gps_timestamp: false,
            show_gps_satellites: false,
            show_gps_status: false,
            show_gps_measure_mode: false,
            show_gps_dop: false,
            show_gps_speed: false,
            show_gps_speed_ref: false,
            show_gps_track: false,
            show_gps_track_ref: false,
            show_gps_img_direction: false,
            show_gps_img_direction_ref: false,
            show_gps_map_datum: false,
            show_gps_date_stamp: false,
            show_gps_processing_method: false,
            show_gps_area_information: false,
            show_gps_differential: false,
            show_gps_h_positioning_error: false,
            show_resolution_unit: false,
            show_photometric_interpretation: false,
            show_compression: false,
            show_bits_per_sample: false,
            show_samples_per_pixel: false,
            show_planar_configuration: false,
            show_ycbcr_sub_sampling: false,
            show_ycbcr_positioning: false,
            show_reference_black_white: false,
            show_white_point: false,
            show_primary_chromaticities: false,
            show_ycbcr_coefficients: false,
            show_water_depth: false,
            show_acceleration: false,
            show_camera_elevation_angle: false,
            show_components_configuration: false,
            show_compressed_bits_per_pixel: false,
            show_file_source: false,
            show_scene_type: false,
            show_cfa_pattern: false,
            show_device_setting_description: false,
            show_subject_area: false,
            show_related_sound_file: false,
            show_spatial_frequency_response: false,
            show_spectral_sensitivity: false,
            show_oecf: false,
            show_width: false,
            show_height: false,
            show_raw_orientation: false,
            show_fuji_rotation_width: false,
            show_camera_mode: false,
            show_remark: false,
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ChartType {
    Bars,
    Lines,
    Points,
}
#[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ApertureScale {
    Linear,
    Logarithmic,
    FStops,
}
